version: '3.4'

services:
  mock-api-npm:
    image: 'node:14'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: node .
    environment:
      - PORT=9090
    ports:
      - 9090:9090

