version: '3.4'

services:
  mock-api-npm:
    image: 'node:14'
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: node .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

